services:
  sCarrega: # Aplicació
    image: icarrega:1.0
    build: .
    expose:
      - "80"
    environment:
      - HOST_NAME=ops15
    networks:
      - carrega
    restart: always
    volumes:
      - .:/var/www/html

  sDc: # Distribuidor de carrega (Nginx)
    image: nginx:latest
    container_name: cNginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sCarrega
    ports:
      - "80:80"
    networks:
      - carrega
    restart: always

networks:
  carrega:
    driver: bridge

